### PR TITLE
add "Compass Compiled!" notification

### PR DESCRIPTION
**Pull request by liorocks**

### CODE REVIEW

**Comment by JoeCianflone** [comment]
I took this out for a couple of reasons: 
1. it seems like more and more elixir plugins were removing the "success" message
2. this message is slightly annoying if you save a lot.  I found myself constantly looking at the corner of my screen...eventually I went "blind" to the messages showing up and then I'd miss the one error message that I do need to see.  

Thoughts?  What if turning on the success message happened via a parameter that you passed in?

**Comment by liorocks** [comment]
I added this, because, when I didn't receive that success message, I thought I was doing something wrong and the compilation wasn't successful. 

After adding it, it was more clear that, everything was working well.

I agree with you, that when saving frequently, those messages can be pretty disturbing. I like the idea of passing parameter, but what about setting it in configurations?

Something like this:

``` js
elixir.config.notifications = {boolean};
```

**Comment by JoeCianflone** [comment]
Yea, I think a config value would be great.

**Comment by liorocks** [comment]
Say your word here: https://github.com/laravel/elixir/issues/63

**Pull request closed without merging**
